
CREATE TABLE public.client_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero text NOT NULL DEFAULT '',
  monto numeric NOT NULL DEFAULT 0,
  nota text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.client_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read" ON public.client_payments FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.client_payments FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.client_payments FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.client_payments FOR DELETE USING (true);
